services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: shamsiddin/manogo
    platform: 'linux/arm64'
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - postgres
      - minio
    volumes:
      - .:/app
    command: sh -c "cd /app && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}

  postgres:
    image: postgres:alpine
    platform: 'linux/arm64'
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    platform: 'linux/arm64'
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    command: server --console-address ":9001" /data

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: shamsiddin/manogo_bot
    platform: 'linux/arm64'
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - .:/app
    command: sh -c "cd /app && python main.py"
volumes:
  postgres_data:
  minio_data: