# Generated by Django 5.0.6 on 2024-09-13 10:28

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('image', models.ImageField(upload_to='category/images', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='competition/images', verbose_name='Image')),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Competition',
                'verbose_name_plural': 'Competitions',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_to', models.IntegerField()),
                ('operator_to', models.IntegerField()),
                ('minimal_sum', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='foydalanuvchi telfon nomeri')),
                ('status', models.CharField(choices=[('admin', 'Admin'), ('currier', 'Currier'), ('operator', 'Operator'), ('user', 'Users'), ('manager', 'Manager')], max_length=20, verbose_name='foydalanuvchi holati')),
                ('main_balance', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='foydalanuvchi balance')),
                ('amount_paid', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='foydalanuvchi tola berilgan sumasi')),
                ('intro', models.TextField(blank=True, default='To enter', max_length=2000, null=True)),
                ('avatar', models.ImageField(blank=True, default='images/icon-256x256.png', null=True, upload_to='users/images', verbose_name='foydalanuvchi avatar rasmi')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='users/banner/images', verbose_name='foydalanuvching banner rasmi')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('is_activate', models.BooleanField(default=False)),
                ('telegram_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.district', verbose_name='Tuman ')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.region', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'verbose_name': 'Admin ',
                'verbose_name_plural': 'Admin Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.user',),
        ),
        migrations.CreateModel(
            name='BalanceReport',
            fields=[
            ],
            options={
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balances',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.user',),
        ),
        migrations.CreateModel(
            name='CurrierUser',
            fields=[
            ],
            options={
                'verbose_name': 'Currier',
                'verbose_name_plural': 'Currie Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.user',),
        ),
        migrations.CreateModel(
            name='ManagerUser',
            fields=[
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Manager Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.user',),
        ),
        migrations.CreateModel(
            name='OperatorUser',
            fields=[
            ],
            options={
                'verbose_name': 'Operator',
                'verbose_name_plural': 'Operator Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.user',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'. Up to 12 digits allowed.", regex='^\\d{7,12}$')])),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('new', 'New'), ('visit', 'Visit'), ('ready', 'Ready'), ('delivery', 'Delivery'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('archived', 'Archived'), ('phone', 'Phone')], default='new', max_length=30)),
                ('street', models.CharField(blank=True, max_length=25, null=True)),
                ('currier', models.ForeignKey(blank=True, limit_choices_to={'status': 'currier'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Currier')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.district', verbose_name='District')),
                ('operator', models.ForeignKey(blank=True, limit_choices_to={'status': 'operator'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_orders', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('referral_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_user', to=settings.AUTH_USER_MODEL, verbose_name="yo'naltiruvchi foydalanuvchi ")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedOrders',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Order',
                'verbose_name_plural': 'Archived Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CanceledOrders',
            fields=[
            ],
            options={
                'verbose_name': 'Canceled Order',
                'verbose_name_plural': 'Canceled Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveredOrders',
            fields=[
            ],
            options={
                'verbose_name': 'Delivered Order',
                'verbose_name_plural': 'Delivered Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrders',
            fields=[
            ],
            options={
                'verbose_name': 'Delivery Order',
                'verbose_name_plural': 'Delivery Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='NewOrders',
            fields=[
            ],
            options={
                'verbose_name': 'New Order',
                'verbose_name_plural': 'New Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PhoneOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Missed Call Order',
                'verbose_name_plural': 'Missed Call Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
        ),
        migrations.CreateModel(
            name='ReadyOrders',
            fields=[
            ],
            options={
                'verbose_name': 'Ready Order',
                'verbose_name_plural': 'Ready Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='VisitOrders',
            fields=[
            ],
            options={
                'verbose_name': 'Visit Order',
                'verbose_name_plural': 'Visit Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PaymeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('progress', 'Progress'), ('canceled', 'Canceled')], default='progress', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='payme/images')),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Mahsulotning Nomi')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Mahsulot haqida ')),
                ('slug', models.SlugField(editable=False, max_length=25, unique=True)),
                ('price', models.IntegerField(verbose_name='Mahsulot narxi')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Mahsulot soni')),
                ('spec', models.JSONField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, default=0, null=True, verbose_name='Mahsulotning chegirmasi')),
                ('user_payment', models.FloatField(blank=True, null=True, verbose_name='Mahsulot sotilgandan keyin userga beriladigan suma')),
                ('referral_reward', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='referal mukafoti')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='apps.category', to_field='slug', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.product', to_field='slug', verbose_name='Product'),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='apps.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='operator_ismi')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.region', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.region', verbose_name='District'),
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('counter', models.IntegerField(default=0, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount', models.PositiveIntegerField(blank=True, null=True)),
                ('benefit', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Stream',
                'verbose_name_plural': 'Streams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='apps.stream', verbose_name='Stream'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.product', verbose_name='wishlist_product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='wishlist_users')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
