# Generated by Django 5.0.6 on 2024-09-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('admin', 'Admin'), ('currier', 'Currier'), ('operator', 'Operator'), ('user', 'Users'), ('manager', 'Manager'), ('seller', 'Seller')], max_length=20, verbose_name='foydalanuvchi holati'),
        ),
    ]
